source 'https://rubygems.org'

rails_version = ENV['RAILS_VERSION'] || '4.0.0'
puts "<---- Installing Rails at version '#{rails_version}'"
gem 'rails', rails_version
gem 'slow_factory_formatter', :path => '..'

gem 'sqlite3', '1.3.11', require: 'sqlite3'
gem 'rspec-rails', '3.4.0'
gem 'factory_girl_rails', '4.7.0'
gem 'rake', '11.1.2'
